### ISSUE TITLE
タグがついた記事の削除ができない

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [elixirjp-slack-com/realworld#6]
# 確認したリビジョン

https://github.com/elixirjp-slack-com/realworld/tree/aba592bacebad22246d842a26f2b7223a4d0beda

# 手順
1. mix setup
2. mix phx.server
3. http://localhost:4000/users/register でユーザをつくる
4. Visit: http://localhost:4000/articles
5. New Articleから記事を新規作成する。タグにはたとえば「Elixir, Phoenix」を入力しておく。
6. 作成した記事のShow 例: http://localhost:4000/articles/2
7. DELETEボタンを押す

# 期待する結果

記事の削除が行えること

# 実際の結果

下記のエラーが発生し、タグがついた記事を削除することができない。

```
[debug] QUERY ERROR db=14.1ms queue=2.6ms idle=1092.3ms
DELETE FROM "articles" WHERE "id" = $1 [2]
[error] GenServer #PID<0.930.0> terminating
** (Ecto.ConstraintError) constraint error when attempting to delete struct:

    * articles_tags_article_id_fkey (foreign_key_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `foreign_key_constraint/3` on your changeset with the constraint
`:name` as an option.

The changeset has not defined any constraint.

    (ecto 3.7.1) lib/ecto/repo/schema.ex:783: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto 3.7.1) lib/ecto/repo/schema.ex:768: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto 3.7.1) lib/ecto/repo/schema.ex:749: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:542: anonymous fn/10 in Ecto.Repo.Schema.do_delete/4
    (realworld 0.1.0) lib/realworld_web/live/article_live/show.ex:51: RealworldWeb.ArticleLive.Show.handle_event/3
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/channel.ex:349: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.0.0) /Users/yamauchimacosamu/books/realworld/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/channel.ex:206: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "55", payload: %{"event" => "delete", "type" => "click", "value" => %{}}, ref: "56", topic: "lv:phx-Fr26v8gh3VgeigOh"}
State: %{components: {%{}, %{}, 1}, join_ref: "55", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, article: %Realworld.Blogs.Article{__meta__: #Ecto.Schema.Metadata<:loaded, "articles">, author: #Ecto.Association.NotLoaded<association :author is not loaded>, author_id: 2, body: "Python", comments: [], id: 2, inserted_at: ~N[2021-12-05 02:29:09], tags: [%Realworld.Blogs.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">, id: 1, inserted_at: ~N[2021-12-05 02:29:09], tag: "Python", updated_at: ~N[2021-12-05 02:29:09]}], title: "aaa", updated_at: ~N[2021-12-05 02:29:09]}, comment_changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [body: {"can't be blank", [validation: :required]}, article_id: {"can't be blank", [validation: :required]}, author_id: {"can't be blank", [validation: :required]}], data: #Realworld.Blogs.Comment<>, valid?: false>, current_user: #Realworld.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirmed_at: nil, email: "awesome2@awesome.com", id: 2, inserted_at: ~N[2021-12-05 02:26:12], updated_at: ~N[2021-12-05 02:26:12], ...>, flash: %{"info" => "User created successfully."}, live_action: :show, page_title: "Show Article"}, endpoint: RealworldWeb.Endpoint, id: "phx-Fr26v8gh3VgeigOh", parent_pid: nil, root_pid: #PID<0.930.0>, router: RealworldWeb.Router, transport_pid: #PID<0.911.0>, view: RealworldWeb.ArticleLive.Show, ...>, topic: "lv:phx-Fr26v8gh3VgeigOh", upload_names: %{}, upload_pids: %{}}
```

# その他

- 記事にタグがついていない場合は削除できる
- 記事にタグをつけて新規作成し、編集にてタグを消して更新後の(タグがない)記事であれば削除できる
- https://github.com/elixirjp-slack-com/realworld/blob/aba592bacebad22246d842a26f2b7223a4d0beda/lib/realworld/blogs/article.ex#L16
- ↑↑↑ を↓↓↓のように変更すると、記事にタグがついた状態でも削除はできた

```
    many_to_many :tags, Tag, join_through: ArticleTag, on_replace: :delete, on_delete: :delete_all
```

- https://hexdocs.pm/ecto/Ecto.Schema.html#many_to_many/3-removing-data

**Comment by TORIFUKUKaiou** [comment]
```elixir
many_to_many :tags, Tag, join_through: ArticleTag, on_replace: :delete, on_delete: :delete_all
```

でよいと考えております。
原稿本文はこの内容で書きます。

https://hexdocs.pm/ecto/Ecto.Schema.html#many_to_many/3-removing-data

記事を消すと、タグ自体は消えずにaritcles_tags中間テーブルのレコードのみが消えます。
